version: '3.1'

services:
    flask:
        build: 
            context: .
        networks:
            - app
        ports:
            - "3000:3000"
        environment:
            DB_URI: "${DB_URI}"
        depends_on:
            - db
        restart: always

    db:
        image: "mysql:8.0"
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "appdb:/var/lib/mysql"
        networks:
            - app
        restart: always

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "5005:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        networks:
            - app

volumes:
  appdb:

networks:
  app:
