name: code integration on main
on:
  pull_request:

concurrency:
  group: prb-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd flask && pip install -r requirements.txt

      - name: Linting
        run: |
          pip install pylint
          cd flask && pylint app.py test_app.py --disable=C0114,C0115 --max-line-length=120 || true
      
      # - name: Run tests
      #   run: |
      #     cd flask && python -m unittest test_app.py

